- name: Oracle DB - Create Linux User Groups
  become_user: root
  ansible.builtin.group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
    state: present
  loop:
    - { group: oinstall, gid: '1001' }
    - { group: dba, gid: '1002' }
    - { group: oper, gid: '1003' }
    - { group: oracle, gid: '1004' }
    - { group: sapsys, gid: '1005' } 
    
    
- name: Oracle DB - Create Linux Users
  become_user: root
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    comment: "{{ item.comment }}"
    append: yes
    state: present
  with_items:
    - { name: 'oracle', uid: '1001', groups: 'oinstall,dba,oper', shell: '/bin/csh', comment: 'Oracle System Administrator' }
    - { name: 'sapadm', uid: '1003', groups: 'sapsys', shell: '/bin/csh', comment: 'Oracle System Administrator' }
    - { name: 'sd1adm', uid: '1002', groups: 'sapsys', shell: '/bin/csh', comment: 'Oracle System Administrator' } 
