---

- name: Oracle DB - Create Linux User Groups
  become_user: root
  ansible.builtin.group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
    state: present
  loop:
    - { group: oinstall, gid: '4001' }
    - { group: dba, gid: '4002' }
    - { group: oper, gid: '4003' }
    - { group: oracle, gid: '4004' }
    - { group: sapsys, gid: '4005' } 
    - { group: sapinst, gid: '4006' }     
    
- name: Oracle DB - Create Linux Users
  become_user: root 
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    comment: "{{ item.comment }}"
    append: yes
    state: present
  with_items:
    - { name: 'oracle', uid: '1001', groups: 'oinstall,dba,oper', shell: '/bin/csh', comment: 'Oracle System Administrator' }
    - { name: 'sapadm', uid: '1003', groups: 'sapsys', shell: '/bin/csh', comment: 'SAP host agent Administrator' } 
    - { name: 'ora{{ GLOBAL_ASCS_SID | lower }}', uid: '1004', groups: 'sapsys,dba,oper', shell: '/bin/csh', comment: 'SAP System Administrator' }
    
- name: useradm - Create Linux Users
  become_user: root 
  vars:
     - passwrd: "{{ GLOBAL_MASTER_PASSWORD }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    comment: "{{ item.comment }}"
    append: yes
    password: "{{ passwrd | password_hash('sha512') }}"
    state: present
  with_items:
    - { name: '{{ GLOBAL_ASCS_SID | lower }}adm', uid: '1002', groups: 'sapsys,sapinst', shell: '/bin/bash', comment: 'SAP System Administrator1' }
   
    

      
