---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Common roles for preparing the image
- name: Check inputs, prepare logs, hostname, install basic dependencies and AWS Data Provider
  become: true
  hosts: all
  roles:
    - role: check-inputs-oracle
      vars:
        input_variables_to_check:
          - EC2_HOSTNAME
          - PRIVATE_DNS_ZONE
          - MASTER_PASSWORD
          - ORACLE_SID
          - ORACLE_INSTANCE_NUMBER
          - EFS_ID
          - S3_BUCKET_MEDIA_FILES
          - ENABLE_HA
          - AWS_CLI_PROFILE
    - role: common-os-tasks-oracle
    - role: prepare-logs-folders-oracle
    - role: install-pkg-mgr-dependencies-oracle
    - role: install-aws-sap-data-provider-oracle
    - role: set-hostname-oracle
      vars:
        extra_vars_to_add_to_hosts:
          - private_ip: "{{ GLOBAL_ASCS_PRIVATE_IP }}"
            hostname: "{{ GLOBAL_ASCS_HOSTNAME }}"
          - private_ip: "{{ GLOBAL_PAS_PRIVATE_IP }}"
            hostname: "{{ GLOBAL_PAS_HOSTNAME }}"

# Installation-specific roles
- name: Set parameters and mount disks
  become: true
  hosts: all
  roles:
    - role: ansible-role-disks
    - role: sap_anydb_install_oracle
