---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Set Global SAP SID for PAS
  set_fact: GLOBAL_SAP_SID="{{ GLOBAL_PAS_SID }}"
  when: GLOBAL_PAS_SID is defined

- name: Set Global SAP SID for ASCS
  set_fact: GLOBAL_SAP_SID="{{ GLOBAL_ASCS_SID }}"
  when: GLOBAL_ASCS_SID is defined and ASCS_SID is defined

- name: Set Global SAP SID for ERS
  set_fact: GLOBAL_SAP_SID="{{ GLOBAL_ERS_SID }}"
  when: GLOBAL_ERS_SID is defined and ERS_SID is defined

- name: Set Global SAP SID for ORACLE
  set_fact: GLOBAL_SAP_SID="{{ GLOBAL_ORACLE_SID }}"
  when: GLOBAL_ORACLE_SID is defined
